// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEvLQBZ-hqBR9vJEvizUgzIAbXSZ0u0jc',
    appId: '1:180007109812:web:f1dd76c50220c245e8c3e1',
    messagingSenderId: '180007109812',
    projectId: 'pratikgtam-portfolio',
    authDomain: 'pratikgtam-portfolio.firebaseapp.com',
    storageBucket: 'pratikgtam-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOyoWm2wkRcnQcZOF6O0tmLRcxgWowms8',
    appId: '1:180007109812:ios:883c8fca59480514e8c3e1',
    messagingSenderId: '180007109812',
    projectId: 'pratikgtam-portfolio',
    storageBucket: 'pratikgtam-portfolio.appspot.com',
    iosBundleId: 'com.example.pratikPortfolio',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0DGJFjwMpk_H-fW3SngxyiDnIgAZG6OI',
    appId: '1:180007109812:android:7e69a1e024276c40e8c3e1',
    messagingSenderId: '180007109812',
    projectId: 'pratikgtam-portfolio',
    storageBucket: 'pratikgtam-portfolio.appspot.com',
  );

}